[package]
name = "synth"
version = "0.1.0"
authors = ["nickchee"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossbeam-channel = "*"
hound = "3.4.0"
jack = "0.6.2"
